void ReadConfig();
bool ReadSerial();
void ParseSerial();
void SaveEvent(unsigned int nEvent);
void SaveZone(unsigned int nZone);
void SaveSensor(unsigned int nSensor);
void AddSensor(byte* pAddress, byte nZone);
void Scan();
int GetTemperature(byte* pAddress);
bool GetTemperature(unsigned int nSensor);
byte getTime(bool bShow);
void setTime(unsigned int nHour, unsigned int nMinute, unsigned int nSecond);
void setDate(unsigned int nDow, unsigned int nDay, unsigned int nMonth, unsigned int nYear);
byte decToBcd(byte nValue);
byte bcdToDec(byte nValue);
void ProcessEvents();
void AddEvent(byte nZone, byte nDays, unsigned int nTime, int nSetpoint, bool bSave = true);
void DeleteEvent(byte nEvent);
byte CharToHex(char nChar);
void OnButtonOk(bool bState);
void OnButtonUpDown(bool bUp);
void ToggleEdit();
